export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";
export const CLEAR_POKEDEX = "CLEAR_POKEDEX";

export const ADD_TO_LINEUP = "ADD_TO_LINEUP";
export const REMOVE_FROM_LINEUP = "REMOVE_FROM_LINEUP";
export const EDIT_LINEUP = "EDIT_LINEUP";
export const SAVE_EDITED_LINEUP = "SAVE_EDITED_LINEUP";
export const CLEAR_POKEMON_FORM = "CLEAR_POKEMON_FORM";

export const FETCH_POKEMON_SETTINGS = "FETCH_POKEMON_SETTINGS";
export const FETCH_POKEMON_SETTINGS_SUCCESS = "FETCH_POKEMON_SETTINGS_SUCCESS";
export const FETCH_POKEMON_SETTINGS_FAILURE = "FETCH_POKEMON_SETTINGS_FAILURE";
